set $term kitty
set $menu rofi -show drun
set $super mod4

bindsym --to-code $super+Return exec $term
bindsym --to-code $super+D exec $menu
bindsym --to-code $super+Shift+Q kill

# add direction vars
set $left H
set $right L
set $up K
set $down J

# focus
bindsym --to-code $super+$left focus left
bindsym --to-code $super+$right focus right
bindsym --to-code $super+$up focus up
bindsym --to-code $super+$down focus down

# move window
bindsym --to-code $super+Shift+$left move left
bindsym --to-code $super+Shift+$right move right
bindsym --to-code $super+Shift+$up move up
bindsym --to-code $super+Shift+$down move down

# focus workspaces
bindsym --to-code $super+1 workspace number 1
bindsym --to-code $super+2 workspace number 2
bindsym --to-code $super+3 workspace number 3
bindsym --to-code $super+4 workspace number 4
bindsym --to-code $super+5 workspace number 5
bindsym --to-code $super+6 workspace number 6
bindsym --to-code $super+7 workspace number 7
bindsym --to-code $super+8 workspace number 8
bindsym --to-code $super+9 workspace number 9
bindsym --to-code $super+0 workspace number 10

# move window to workspaces
bindsym --to-code $super+Shift+1 move container to workspace number 1
bindsym --to-code $super+Shift+2 move container to workspace number 2
bindsym --to-code $super+Shift+3 move container to workspace number 3
bindsym --to-code $super+Shift+4 move container to workspace number 4
bindsym --to-code $super+Shift+5 move container to workspace number 5
bindsym --to-code $super+Shift+6 move container to workspace number 6
bindsym --to-code $super+Shift+7 move container to workspace number 7
bindsym --to-code $super+Shift+8 move container to workspace number 8
bindsym --to-code $super+Shift+9 move container to workspace number 9
bindsym --to-code $super+Shift+0 move container to workspace number 10

# scratchpad
bindsym --to-code $super+S scratchpad show
bindsym --to-code $super+Shift+S move scratchpad

# reload
bindsym --to-code $super+Shift+r reload

# layouts
bindsym --to-code $super+backslash splitt
bindsym --to-code $super+Shift+backslash layout toggle split
bindsym --to-code $super+w layout tabbed
bindsym --to-code $super+f floating toggle
bindsym --to-code $super+Shift+f fullscreen
floating_modifier $super normal

# Special keys to adjust volume via PulseAudio
bindsym --locked XF86AudioMute exec pactl set-sink-mute \@DEFAULT_SINK@ toggle
bindsym --locked XF86AudioLowerVolume exec pactl set-sink-volume \@DEFAULT_SINK@ -5%
bindsym --locked XF86AudioRaiseVolume exec pactl set-sink-volume \@DEFAULT_SINK@ +5%
bindsym --locked XF86AudioMicMute exec pactl set-source-mute \@DEFAULT_SOURCE@ toggle

# Special keys to control media via playerctl
bindsym --locked XF86AudioPlay exec playerctl play-pause
bindsym --locked XF86AudioPause exec playerctl play-pause
bindsym --locked XF86AudioPrev exec playerctl previous
bindsym --locked XF86AudioNext exec playerctl next
bindsym --locked XF86AudioStop exec playerctl stop

# Special keys to adjust brightness via brightnessctl
bindsym --locked XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym --locked XF86MonBrightnessUp exec brightnessctl set 5%+

bindsym --to-code $super+Minus resize shrink width 10px
bindsym --to-code $super+Equal resize grow width 10px
bindsym --to-code $super+Shift+Minus resize shrink height 10px
bindsym --to-code $super+Shift+Equal resize grow height 10px
