set $term kitty
set $menu rofi -show drun
set $super $mod4

bindsym --to-code $super+Return exec $term
bindsym --to-code $super+D exec $menu

# add direction vars
set $left H
set $right L
set $up K
set $down J

# focus
bindsym --to-code $super+$left         focus left
bindsym --to-code $super+$right        focus right
bindsym --to-code $super+$up           focus up
bindsym --to-code $super+$down         focus down

# move window
bindsym --to-code $super+Shift+$left   move left
bindsym --to-code $super+Shift+$right  move right
bindsym --to-code $super+Shift+$up     move up
bindsym --to-code $super+Shift+$down   move down
