# colors
client.focused #ff6767 #ff6767 #ffffff #ffffff #ff6767
client.unfocused #232323 #232323 #ffffff #ffffff #232323
client.urgent #ff0000 #ff0000 #ffffff #ffffff #ff0000

# font
font "Ubuntu Mono Bold" 12

# gaps
gaps inner 5
gaps outer 5

# border
default_border normal 4
titlebar_border_thickness 1
title_align center
